import { CakeAuthProvider } from "@cakeauth/nextjs-app";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CakeAuthProvider
          config={{
            publicKey: process.env.NEXT_PUBLIC_CAKEAUTH_PUBLIC_KEY!,
          }}
        >
          {children}
        </CakeAuthProvider>
      </body>
    </html>
  );
}
